/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SidePanel.java
 *
 * Created on Nov 13, 2011, 1:06:16 PM
 */
package javasnakes.gui;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javasnakes.model.GlobalConstants;
import javax.imageio.ImageIO;

/**
 * This implements the UI containing the game options, seed panel, and die area.
 * @author Group 1, CPE 316 (2010/2011)
 * @version 1.0
 */
public class SidePanel extends javax.swing.JPanel {

    /**
     * Creates new form SidePanel 
     */
    public SidePanel() {
	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movesLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dieLabel = new javax.swing.JLabel();
        dieButton = new javax.swing.JButton();
        buttomSnakePanel = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2D = (Graphics2D) g;
                Image gameSnake = null;
                try {
                    gameSnake = ImageIO.read(getClass().getResourceAsStream("/game_snake2.png"));
                } catch (IOException ex) {
                    Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "Unable to load the snake image.");
                }
                g2D.setRenderingHints(GlobalConstants.qualityHints);
                g2D.drawImage(gameSnake, 0, 0, this.getSize().width, this.getSize().height, this);
                g2D.setFont(new java.awt.Font("Comic Sans", Font.BOLD, 14));
                g2D.setColor(java.awt.Color.DARK_GRAY);
                g2D.drawString("I'm gonna", 10, this.getHeight() - 20);
                g2D.drawString("finish you!", 10, this.getHeight() - 5);
            }
        };
        seedsPanel = new javasnakes.gui.SeedsPanel();
        notificationsLabel = new javax.swing.JLabel();

        setOpaque(false);

        movesLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        movesLabel.setText("Moves: ");

        timeLabel.setVisible(false);
        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 14));
        timeLabel.setText("Time: ");

        dieLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dieLabel.setIcon(null);
        dieLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        dieButton.setText("Roll Die");
        dieButton.setEnabled(false);
        dieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieButtonActionPerformed(evt);
            }
        });

        buttomSnakePanel.setOpaque(false);

        javax.swing.GroupLayout buttomSnakePanelLayout = new javax.swing.GroupLayout(buttomSnakePanel);
        buttomSnakePanel.setLayout(buttomSnakePanelLayout);
        buttomSnakePanelLayout.setHorizontalGroup(
            buttomSnakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        buttomSnakePanelLayout.setVerticalGroup(
            buttomSnakePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );

        seedsPanel.setOpaque(false);

        javax.swing.GroupLayout seedsPanelLayout = new javax.swing.GroupLayout(seedsPanel);
        seedsPanel.setLayout(seedsPanelLayout);
        seedsPanelLayout.setHorizontalGroup(
            seedsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        seedsPanelLayout.setVerticalGroup(
            seedsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        notificationsLabel.setFont(movesLabel.getFont());
        notificationsLabel.setForeground(new java.awt.Color(255, 0, 0));
        notificationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(timeLabel)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(dieButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(seedsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(dieLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificationsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(buttomSnakePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notificationsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(seedsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(dieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dieButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(buttomSnakePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieButtonActionPerformed
	//notify the game board that the RollDie button has been clicked.
	BoardImpl.getInstance().dieButtonActionPerformed(evt);
    }//GEN-LAST:event_dieButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttomSnakePanel;
    private javax.swing.JButton dieButton;
    private javax.swing.JLabel dieLabel;
    private javax.swing.JLabel movesLabel;
    private javax.swing.JLabel notificationsLabel;
    private javasnakes.gui.SeedsPanel seedsPanel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the buttomSnakePanel
     */
    public javax.swing.JPanel getButtomSnakePanel() {
	return buttomSnakePanel;
    }

    /**
     * @return the dieButton
     */
    public javax.swing.JButton getDieButton() {
	return dieButton;
    }

    /**
     * @return the dieLabel
     */
    public javax.swing.JLabel getDieLabel() {
	return dieLabel;
    }

    /**
     * @return the movesLabel
     */
    public javax.swing.JLabel getMovesLabel() {
	return movesLabel;
    }

    /**
     * @return the seedsPanel
     */
    public javasnakes.gui.SeedsPanel getSeedsPanel() {
	return seedsPanel;
    }

    /**
     * @return the timeLabel
     */
    public javax.swing.JLabel getTimeLabel() {
	return timeLabel;
    }

    /**
     * @return the notificationsLabel
     */
    public javax.swing.JLabel getNotificationsLabel() {
        return notificationsLabel;
    }
}
